export const LOGIN = "USER_LOGIN";
export const LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const LOGIN_FAILED = "USER_LOGIN_FAILED";
export const SIGN_UP = "USER_SIGN_UP";
export const SIGN_UP_FAILED = "USER_SIGN_UP_FAILED";
export const FROM_DATABASE = "USER_FROM_DATABASE";
export const SELECT = "USER_SELECT";
export const BASIC_DETAILS_FROM_SERVER = "USER_BASIC_DETAILS_FROM_SERVER";

